# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Network Shares - Ksmbd the SMB kernel fileserver
LUCI_DEPENDS:=+ksmbd-server

PKG_NAME:=luci-app-ksmbd
PKG_VERSION:=1
PKG_RELEASE:=13

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
