#!/bin/sh

if [ "$(uci -q get luci.diag)" != "internal" ]; then
	host=""

	if [ -s /etc/os-release ]; then
		. /etc/os-release
		host="${HOME_URL:-${BUG_URL:-$LEDE_DEVICE_MANUFACTURER_URL}}"
		host="${host#*://}"
		host="${host%%/*}"
	fi

	uci -q batch <<-EOF >/dev/null
		set luci.diag=internal
		set luci.diag.dns='${host:-openwrt.org}'
		set luci.diag.ping='${host:-openwrt.org}'
		set luci.diag.route='${host:-openwrt.org}'
		commit luci
	EOF
fi

[ -n "$(command -v cpuinfo)" -a -n "$(command -v ethinfo)" -a -f /usr/lib/lua/luci/view/admin_status/index_x86.htm ] && mv /usr/lib/lua/luci/view/admin_status/index_x86.htm /usr/lib/lua/luci/view/admin_status/index.htm
rm -rf /usr/lib/lua/luci/view/admin_status/index_x86.htm

exit 0
