# Copyright (C) 2018-2021 Lienol <lawlienol@gmail.com>
#
# This is free software, licensed under the GNU General Public License v3.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Bootstrap Mod Theme By Lienol
LUCI_DEPENDS:=
PKG_VERSION:=1.14
PKG_DATE:=20210626

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
